---
name: Application Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Force HTTPS for GitHub
        run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/

      - name: Corepack Enable Yarn
        run: corepack enable yarn

      - name: Setup Node (v20)
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: "20.x"

      - name: Install dependencies
        run: yarn --immutable

      - name: Build
        run: yarn make

      - name: Upload artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ytmdesktop-windows
          path: out/make/**/*

      - name: Upload artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ytmdesktop-linux
          path: out/make/**/*

      - name: Upload artifacts (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ytmdesktop-macos
          path: out/make/**/*
